config/routes.rb
Prelude::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  match 'user_root' => redirect("/edit")
  
  get '/about' => 'pages#show', :defaults => {:key => 'about'}
  get '/about/:key' => 'pages#show'
  get '/profile/:id' => 'profiles#show', :as => :profile
  
  root :to => 'static#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:email]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates_presence_of :key

  auto_strip_attributes :key, :title, :content
end

app/models/site_settings.rb
class SiteSettings < Settingslogic
  source "#{Rails.root}/config/site.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :thumb => "50x50#", :medium => "250x250#" }
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :username, :email, :password, :password_confirmation, :remember_me, :avatar
  attr_accessor :login

  auto_strip_attributes :username, :email

  validates :email, :uniqueness => { :case_sensitive => false }
  validates :username, :uniqueness => { :case_sensitive => false }, :length => { :maximum => 42, :minimum => 4 }
  validates_attachment_content_type  :avatar, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
  validates_attachment_size :avatar, :in => 0..10.megabytes
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.strip.downcase }]).first
  end

  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end
    update_attributes(params) 
  end

  def to_s
    username
  end

  protected

  # Attempt to find a user by it's email. If a record is found, send new
  # password instructions to it. If not user is found, returns a new user
  # with an email not found error.
  def self.send_reset_password_instructions(attributes={})
  	recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
  	recoverable.send_reset_password_instructions if recoverable.persisted?
  	recoverable
  end 
 
  def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, error=:invalid)
  	(case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }
   
  	attributes = attributes.slice(*required_attributes)
  	attributes.delete_if { |key, value| value.blank? }
   
  	if attributes.size == required_attributes.size
  	  if attributes.has_key?(:login)
  		 login = attributes[:login]
  		 record = find_record(login)
  	  else  
  		record = where(attributes).first
  	  end  
  	end  
   
  	unless record
  	  record = new
   
  	  required_attributes.each do |key|
  		value = attributes[key]
  		record.send("#{key}=", value)
  		record.errors.add(key, value.present? ? error : :blank)
  	  end  
  	end  
  	record
  end
 
  def self.find_record(login)
  	where(["username = :value OR email = :value", { :value => login }]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  if !Rails.application.config.consider_all_requests_local
    rescue_from Exception, with: :render_500
    rescue_from ActionController::RoutingError, with: :render_404
    rescue_from ActionController::UnknownController, with: :render_404
    rescue_from ActionController::UnknownAction, with: :render_404
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
  end

  protected
  
  def render_404(exception=nil)
    if !exception.blank?
      message = exception.message
      trace = exception.backtrace.join("\n ")
      logger.error message + "\n " + trace
    end
    respond_to do |format|
      format.html { render template: 'errors/404', layout: 'layouts/application', status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end

  def render_500(exception=nil)
    if !exception.blank?
      message = exception.message
      trace = exception.backtrace.join("\n ")
      logger.error message + "\n " + trace
    end
    respond_to do |format|
      format.html { render template: 'errors/500', layout: 'layouts/application', status: 500 }
      format.all { render nothing: true, status: 500}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_key(params[:key])
    render_404 if @page.blank?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    render_404 if @user.blank?
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title=nil)
    if page_title.nil?
      return get_page_title
    end
    @page_title = page_title
  end
  
  def get_page_title
    if !@page_title.blank?
      separator = " | "
      if @page_title.is_a?(Array)
        @page_title = @page_title.reverse.join(separator)
      end
      "#{@page_title}#{separator}#{SiteSettings.site_name}"
    else
      SiteSettings.site_name
    end
  end
  
  def truncate_to_space(string, length=100, options={})
    defaults = {
      :length => length,
      :separator => ' '
    }
    options = defaults.merge(options)
    truncate(string, options)
  end
end

app/helpers/cache_helper.rb
module CacheHelper
  def cache_if_not_signed_in(*args)
    if !user_signed_in?
      cache args do
        yield
      end
    else
      yield
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def markdown(string)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    renderer.render(string).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar(user, options={})
    defaults = {
      :class => 'avatar',
      :div => true,
      :link => false,
      :html => {},
      :size => :medium
    }
    options.reverse_merge!(defaults)
    html = image_tag(user.avatar.url(options[:size]), options[:html])
    if options[:link]
      html = link_to(html, user_path(user))
    end
    if options[:div]
      html = '<div class="'+options[:class]+'">'+html+'</div>'
    end
    html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= page_title %></title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/"><%= SiteSettings.site_name %></a>
          
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.to_s %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", profile_path(current_user) %></li>
                    <li><%= link_to "Settings", edit_user_registration_path %></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign in | Sign Up", new_user_session_path, :class => 'login-link' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div id="wrap">
      <div id="main" class="container primary-<%= params[:controller] %> secondary-<%= params[:action] %>">
        <% flash.each do |name, msg| %> 
          <%= content_tag :section, msg, :id => "flash_#{name}", :class => "flash" %> 
        <% end %>
        <%= yield %>
      </div>
    </div>
    
    <div class="footer">
      <div class="container">
        <ul class="nav nav-pills">
          <li><%= link_to "About", "/about" %></li>
          <li><%= link_to "Contact", "/about/contact" %></li>
          <li><%= link_to "Terms", "/about/terms" %></li>
        </ul>
      </div>
    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/show.html.erb
<% page_title @page.title %>

<h2><%= @page.title %></h2>

<div class="page-content markdown">
  <%= markdown(@page.content) %>
</div>

app/views/profiles/show.html.erb
<% page_title @user.to_s %>

<h2><%= @user.to_s %></h2>